services:
  db:
    image: postgres
    restart: always
    env_file: ./.db.env
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  zitadel:
    restart: always
    image: ghcr.io/zitadel/zitadel:latest
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    env_file: ./.zitadel.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  # server:
  #   build: ./server
  #   restart: always
  #   env_file: ./.server.env
  #   ports:
  #     - 8181:8181
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  dbdata:
